package handler

import (
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"strings"
)

// HandleSubscriptionVless returns a base64-encoded VLESS subscription.
func (h *Handler) HandleSubscriptionVless(w http.ResponseWriter, r *http.Request) {
	nodes, err := h.queryAllNodes()
	if err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}

	var links []string
	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := buildNodeName(n)
		params := url.Values{}
		params.Set("type", "ws")
		params.Set("security", "tls")
		params.Set("sni", host)
		params.Set("path", fmt.Sprintf("/%s?ed=2560", h.Config.XrayPath))
		link := fmt.Sprintf("vless://%s@%s:443?%s#%s",
			n.XrayUUID, host, params.Encode(), url.PathEscape(name))
		links = append(links, link)
	}

	content := base64.StdEncoding.EncodeToString([]byte(strings.Join(links, "\n")))
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=hive-subscription.txt")
	fmt.Fprint(w, content)
}

// HandleSubscriptionClash returns a Clash/Mihomo YAML subscription.
func (h *Handler) HandleSubscriptionClash(w http.ResponseWriter, r *http.Request) {
	nodes, err := h.queryAllNodes()
	if err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}

	var proxyNames []string
	var proxies strings.Builder

	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := buildNodeName(n)
		proxyNames = append(proxyNames, "    - "+yamlStr(name))

		fmt.Fprintf(&proxies, `  - name: %s
    type: vless
    server: %s
    port: 443
    uuid: %s
    network: ws
    tls: true
    servername: %s
    ws-opts:
      path: /%s
      headers:
        Host: %s
      max-early-data: 2560
      early-data-header-name: Sec-WebSocket-Protocol
`, yamlStr(name), host, n.XrayUUID, host, h.Config.XrayPath, host)
	}

	yaml := &strings.Builder{}
	fmt.Fprintln(yaml, "# Hive Node Registry - Clash/Mihomo subscription")
	fmt.Fprintln(yaml, "# Generated by hive-registry")
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxies:")
	fmt.Fprint(yaml, proxies.String())
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxy-groups:")
	fmt.Fprintln(yaml, "  - name: HIVE-AUTO")
	fmt.Fprintln(yaml, "    type: url-test")
	fmt.Fprintln(yaml, "    url: http://www.gstatic.com/generate_204")
	fmt.Fprintln(yaml, "    interval: 300")
	fmt.Fprintln(yaml, "    proxies:")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "  - name: HIVE-SELECT")
	fmt.Fprintln(yaml, "    type: select")
	fmt.Fprintln(yaml, "    proxies:")
	fmt.Fprintln(yaml, "    - HIVE-AUTO")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "rules:")
	fmt.Fprintln(yaml, "  - MATCH,HIVE-SELECT")

	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", "attachment; filename=hive-clash.yaml")
	fmt.Fprint(w, yaml.String())
}
