package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"hive/registry/internal/middleware"
	"hive/registry/internal/model"

	"gorm.io/gorm"
)

type CreateGroupRequest struct {
	Name string `json:"name"`
}

type SetGroupNodesRequest struct {
	Nodes []string `json:"nodes"`
}

type ResetTokenResponse struct {
	Token string `json:"token"`
}

// buildGroupClashYAML generates a group-specific Clash YAML.
func (h *Handler) buildGroupClashYAML(groupName string, nodes []model.Node) string {
	var proxyNames []string
	var proxies strings.Builder

	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := buildNodeName(n)
		proxyNames = append(proxyNames, "    - "+yamlStr(name))
		fmt.Fprintf(&proxies, `  - name: %s
    type: vless
    server: %s
    port: 443
    uuid: %s
    network: ws
    tls: true
    servername: %s
    ws-opts:
      path: /%s
      headers:
        Host: %s
      max-early-data: 2560
      early-data-header-name: Sec-WebSocket-Protocol
`, yamlStr(name), host, n.XrayUUID, host, h.Config.XrayPath, host)
	}

	autoName := groupName + "-AUTO"
	selectName := groupName + "-SELECT"

	yaml := &strings.Builder{}
	fmt.Fprintf(yaml, "# Hive Node Registry - %s\n", groupName)
	fmt.Fprintln(yaml, "# Generated by hive-registry")
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxies:")
	fmt.Fprint(yaml, proxies.String())
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxy-groups:")
	fmt.Fprintf(yaml, "  - name: %s\n", autoName)
	fmt.Fprintln(yaml, "    type: url-test")
	fmt.Fprintln(yaml, "    url: http://www.gstatic.com/generate_204")
	fmt.Fprintln(yaml, "    interval: 300")
	fmt.Fprintln(yaml, "    proxies:")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintf(yaml, "  - name: %s\n", selectName)
	fmt.Fprintln(yaml, "    type: select")
	fmt.Fprintln(yaml, "    proxies:")
	fmt.Fprintf(yaml, "    - %s\n", autoName)
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintf(yaml, "rules:\n  - MATCH,%s\n", selectName)

	return yaml.String()
}

// HandleListGroups handles GET /admin/subscription-groups
func (h *Handler) HandleListGroups(w http.ResponseWriter, r *http.Request) {
	groups := make([]model.SubscriptionGroup, 0)
	if err := h.DB.Raw("SELECT g.id, g.name, g.token, COUNT(gn.node_mac) AS node_count, g.created_at, g.updated_at FROM subscription_groups g LEFT JOIN subscription_group_nodes gn ON gn.group_id = g.id GROUP BY g.id ORDER BY g.id").Scan(&groups).Error; err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	h.jsonOK(w, groups)
}

// HandleCreateGroup handles POST /admin/subscription-groups
func (h *Handler) HandleCreateGroup(w http.ResponseWriter, r *http.Request) {
	var req CreateGroupRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	req.Name = strings.TrimSpace(req.Name)
	if req.Name == "" {
		h.jsonErr(w, http.StatusBadRequest, "name is required")
		return
	}

	token, err := generateToken()
	if err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "token: "+err.Error())
		return
	}

	now := time.Now().UTC().Format("2006-01-02 15:04:05")
	if err := h.DB.Exec(
		"INSERT INTO subscription_groups (name, token, created_at, updated_at) VALUES (?, ?, ?, ?)",
		req.Name, token, now, now,
	).Error; err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	var id uint
	h.DB.Raw("SELECT LAST_INSERT_ID()").Scan(&id)
	h.jsonOK(w, model.SubscriptionGroup{
		ID:        id,
		Name:      req.Name,
		Token:     token,
		NodeCount: 0,
		CreatedAt: now,
		UpdatedAt: now,
	})
}

// HandleDeleteGroup handles DELETE /admin/subscription-groups/{id}
func (h *Handler) HandleDeleteGroup(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var name string
	if err := h.DB.Raw("SELECT name FROM subscription_groups WHERE id=?", id).Scan(&name).Error; err != nil || name == "" {
		h.jsonErr(w, http.StatusNotFound, "group not found")
		return
	}
	if err := h.DB.Exec("DELETE FROM subscription_groups WHERE id=?", id).Error; err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	h.jsonOK(w, map[string]string{"status": "ok"})
}

// HandleGetGroupNodes handles GET /admin/subscription-groups/{id}/nodes
func (h *Handler) HandleGetGroupNodes(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int64
	if err := h.DB.Table("subscription_groups").Where("id=?", id).Count(&cnt).Error; err != nil || cnt == 0 {
		h.jsonErr(w, http.StatusNotFound, "group not found")
		return
	}
	var macs []string
	if err := h.DB.Model(&model.SubscriptionGroupNode{}).Where("group_id=?", id).Order("node_mac").Pluck("node_mac", &macs).Error; err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	if macs == nil {
		macs = make([]string, 0)
	}
	h.jsonOK(w, macs)
}

// HandleSetGroupNodes handles PUT /admin/subscription-groups/{id}/nodes
func (h *Handler) HandleSetGroupNodes(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int64
	if err := h.DB.Table("subscription_groups").Where("id=?", id).Count(&cnt).Error; err != nil || cnt == 0 {
		h.jsonErr(w, http.StatusNotFound, "group not found")
		return
	}

	var req SetGroupNodesRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	if req.Nodes == nil {
		req.Nodes = []string{}
	}

	if err := h.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("group_id=?", id).Delete(&model.SubscriptionGroupNode{}).Error; err != nil {
			return err
		}
		for _, mac := range req.Nodes {
			tx.Exec("INSERT IGNORE INTO subscription_group_nodes (group_id, node_mac) VALUES (?, ?)", id, mac)
		}
		now := time.Now().UTC().Format("2006-01-02 15:04:05")
		tx.Exec("UPDATE subscription_groups SET updated_at=? WHERE id=?", now, id)
		return nil
	}); err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	h.jsonOK(w, map[string]string{"status": "ok"})
}

// HandleResetGroupToken handles POST /admin/subscription-groups/{id}/reset-token
func (h *Handler) HandleResetGroupToken(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		h.jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int64
	if err := h.DB.Table("subscription_groups").Where("id=?", id).Count(&cnt).Error; err != nil || cnt == 0 {
		h.jsonErr(w, http.StatusNotFound, "group not found")
		return
	}

	token, err := generateToken()
	if err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "token: "+err.Error())
		return
	}
	now := time.Now().UTC().Format("2006-01-02 15:04:05")
	if err := h.DB.Exec("UPDATE subscription_groups SET token=?, updated_at=? WHERE id=?", token, now, id).Error; err != nil {
		h.jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	h.jsonOK(w, ResetTokenResponse{Token: token})
}

// HandlePublicGroupClash handles GET /s/{token}
func (h *Handler) HandlePublicGroupClash(w http.ResponseWriter, r *http.Request) {
	middleware.SubscriptionRequestsTotal.WithLabelValues("public_group_clash").Inc()

	token := r.PathValue("token")
	if len(token) != 64 {
		http.NotFound(w, r)
		return
	}

	var sg struct {
		ID   uint
		Name string
	}
	if err := h.DB.Raw("SELECT id, name FROM subscription_groups WHERE token=?", token).Scan(&sg).Error; err != nil || sg.ID == 0 {
		http.NotFound(w, r)
		return
	}

	var macs []string
	if err := h.DB.Model(&model.SubscriptionGroupNode{}).Where("group_id=?", sg.ID).Pluck("node_mac", &macs).Error; err != nil {
		http.Error(w, "db error", http.StatusInternalServerError)
		return
	}

	nodes, err := h.queryNodesByMACs(macs)
	if err != nil {
		http.Error(w, "db error", http.StatusInternalServerError)
		return
	}

	yaml := h.buildGroupClashYAML(sg.Name, nodes)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="hive-%s.yaml"`, sg.Name))
	fmt.Fprint(w, yaml)
}
