package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"
)

// ── 数据结构 ──────────────────────────────────────────────────────────────────

type SubscriptionGroup struct {
	ID        uint   `json:"id"`
	Name      string `json:"name"`
	Token     string `json:"token"`
	NodeCount int    `json:"node_count"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CreateGroupRequest struct {
	Name string `json:"name"`
}

type SetGroupNodesRequest struct {
	Nodes []string `json:"nodes"`
}

// ResetTokenResponse is the JSON body for POST /admin/subscription-groups/{id}/reset-token.
type ResetTokenResponse struct {
	Token string `json:"token"`
}

// ── 工具函数 ──────────────────────────────────────────────────────────────────

func generateToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// queryNodesByMACs 按 MAC 列表查询节点，保持顺序。
func queryNodesByMACs(macs []string) ([]Node, error) {
	if len(macs) == 0 {
		return nil, nil
	}
	placeholders := strings.Repeat("?,", len(macs))
	placeholders = placeholders[:len(placeholders)-1]
	args := make([]interface{}, len(macs))
	for i, m := range macs {
		args[i] = m
	}
	rows, err := db.Query(
		"SELECT "+nodeCols+" FROM nodes WHERE mac IN ("+placeholders+") ORDER BY hostname",
		args...,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var nodes []Node
	for rows.Next() {
		n, err := scanNode(rows)
		if err != nil {
			return nil, err
		}
		nodes = append(nodes, n)
	}
	return nodes, nil
}

// buildGroupClashYAML 生成分组专属的 Clash YAML，复用 subscription.go 的工具函数。
func buildGroupClashYAML(groupName string, nodes []Node) string {
	var proxyNames []string
	var proxies strings.Builder

	for _, n := range nodes {
		host := stripScheme(n.CFURL)
		if host == "" || n.XrayUUID == "" {
			continue
		}
		name := buildNodeName(n)
		proxyNames = append(proxyNames, "    - "+yamlStr(name))
		fmt.Fprintf(&proxies, `  - name: %s
    type: vless
    server: %s
    port: 443
    uuid: %s
    network: ws
    tls: true
    servername: %s
    ws-opts:
      path: /%s
      headers:
        Host: %s
      max-early-data: 2560
      early-data-header-name: Sec-WebSocket-Protocol
`, yamlStr(name), host, n.XrayUUID, host, xrayPath, host)
	}

	autoName := groupName + "-AUTO"
	selectName := groupName + "-SELECT"

	yaml := &strings.Builder{}
	fmt.Fprintf(yaml, "# Hive Node Registry - %s\n", groupName)
	fmt.Fprintln(yaml, "# Generated by hive-registry")
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxies:")
	fmt.Fprint(yaml, proxies.String())
	fmt.Fprintln(yaml, "")
	fmt.Fprintln(yaml, "proxy-groups:")
	fmt.Fprintf(yaml, "  - name: %s\n", autoName)
	fmt.Fprintln(yaml, "    type: url-test")
	fmt.Fprintln(yaml, "    url: http://www.gstatic.com/generate_204")
	fmt.Fprintln(yaml, "    interval: 300")
	fmt.Fprintln(yaml, "    proxies:")
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintf(yaml, "  - name: %s\n", selectName)
	fmt.Fprintln(yaml, "    type: select")
	fmt.Fprintln(yaml, "    proxies:")
	fmt.Fprintf(yaml, "    - %s\n", autoName)
	for _, name := range proxyNames {
		fmt.Fprintln(yaml, name)
	}
	fmt.Fprintln(yaml, "")
	fmt.Fprintf(yaml, "rules:\n  - MATCH,%s\n", selectName)

	return yaml.String()
}

// ── Handlers ──────────────────────────────────────────────────────────────────

// GET /admin/subscription-groups
//
// @Summary List subscription groups
// @Tags admin
// @Produce application/json
// @Success 200 {array} SubscriptionGroup
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups [get]
// @ID AdminListSubscriptionGroups
func handleListGroups(w http.ResponseWriter, r *http.Request) {
	rows, err := db.Query(`
		SELECT g.id, g.name, g.token, COUNT(gn.node_mac) AS node_count, g.created_at, g.updated_at
		FROM subscription_groups g
		LEFT JOIN subscription_group_nodes gn ON gn.group_id = g.id
		GROUP BY g.id
		ORDER BY g.id
	`)
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	defer rows.Close()

	groups := make([]SubscriptionGroup, 0)
	for rows.Next() {
		var g SubscriptionGroup
		if err := rows.Scan(&g.ID, &g.Name, &g.Token, &g.NodeCount, &g.CreatedAt, &g.UpdatedAt); err != nil {
			jsonErr(w, http.StatusInternalServerError, "scan: "+err.Error())
			return
		}
		groups = append(groups, g)
	}
	jsonOK(w, groups)
}

// POST /admin/subscription-groups
//
// @Summary Create subscription group
// @Tags admin
// @Accept json
// @Produce application/json
// @Param body body CreateGroupRequest true "group name"
// @Success 200 {object} SubscriptionGroup
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups [post]
// @ID AdminCreateSubscriptionGroup
func handleCreateGroup(w http.ResponseWriter, r *http.Request) {
	var req CreateGroupRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	req.Name = strings.TrimSpace(req.Name)
	if req.Name == "" {
		jsonErr(w, http.StatusBadRequest, "name is required")
		return
	}

	token, err := generateToken()
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "token: "+err.Error())
		return
	}

	now := time.Now().UTC().Format("2006-01-02 15:04:05")
	res, err := db.Exec(
		"INSERT INTO subscription_groups (name, token, created_at, updated_at) VALUES (?, ?, ?, ?)",
		req.Name, token, now, now,
	)
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	id, _ := res.LastInsertId()
	jsonOK(w, SubscriptionGroup{
		ID:        uint(id),
		Name:      req.Name,
		Token:     token,
		NodeCount: 0,
		CreatedAt: now,
		UpdatedAt: now,
	})
}

// DELETE /admin/subscription-groups/{id}
//
// @Summary Delete subscription group
// @Tags admin
// @Produce application/json
// @Param id path int true "group id"
// @Success 200 {object} StatusResponse
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 404 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups/{id} [delete]
// @ID AdminDeleteSubscriptionGroup
func handleDeleteGroup(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var name string
	if err := db.QueryRow("SELECT name FROM subscription_groups WHERE id=?", id).Scan(&name); err != nil {
		jsonErr(w, http.StatusNotFound, "group not found")
		return
	}
	if _, err := db.Exec("DELETE FROM subscription_groups WHERE id=?", id); err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	jsonOK(w, StatusResponse{Status: "ok"})
}

// GET /admin/subscription-groups/{id}/nodes
//
// @Summary List node MACs in a subscription group
// @Tags admin
// @Produce application/json
// @Param id path int true "group id"
// @Success 200 {array} string
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 404 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups/{id}/nodes [get]
// @ID AdminGetSubscriptionGroupNodes
func handleGetGroupNodes(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int
	if err := db.QueryRow("SELECT COUNT(*) FROM subscription_groups WHERE id=?", id).Scan(&cnt); err != nil || cnt == 0 {
		jsonErr(w, http.StatusNotFound, "group not found")
		return
	}
	rows, err := db.Query("SELECT node_mac FROM subscription_group_nodes WHERE group_id=? ORDER BY node_mac", id)
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	defer rows.Close()
	macs := make([]string, 0)
	for rows.Next() {
		var mac string
		if rows.Scan(&mac) == nil {
			macs = append(macs, mac)
		}
	}
	jsonOK(w, macs)
}

// PUT /admin/subscription-groups/{id}/nodes
//
// @Summary Replace node MACs in a subscription group
// @Tags admin
// @Accept json
// @Produce application/json
// @Param id path int true "group id"
// @Param body body SetGroupNodesRequest true "node MAC list"
// @Success 200 {object} StatusResponse
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 404 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups/{id}/nodes [put]
// @ID AdminSetSubscriptionGroupNodes
func handleSetGroupNodes(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int
	if err := db.QueryRow("SELECT COUNT(*) FROM subscription_groups WHERE id=?", id).Scan(&cnt); err != nil || cnt == 0 {
		jsonErr(w, http.StatusNotFound, "group not found")
		return
	}

	var req SetGroupNodesRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid JSON: "+err.Error())
		return
	}
	if req.Nodes == nil {
		req.Nodes = []string{}
	}

	tx, err := db.Begin()
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "tx: "+err.Error())
		return
	}
	defer tx.Rollback()

	if _, err := tx.Exec("DELETE FROM subscription_group_nodes WHERE group_id=?", id); err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	for _, mac := range req.Nodes {
		tx.Exec("INSERT IGNORE INTO subscription_group_nodes (group_id, node_mac) VALUES (?, ?)", id, mac)
	}
	now := time.Now().UTC().Format("2006-01-02 15:04:05")
	tx.Exec("UPDATE subscription_groups SET updated_at=? WHERE id=?", now, id)

	if err := tx.Commit(); err != nil {
		jsonErr(w, http.StatusInternalServerError, "commit: "+err.Error())
		return
	}
	jsonOK(w, StatusResponse{Status: "ok"})
}

// POST /admin/subscription-groups/{id}/reset-token
//
// @Summary Reset subscription group token
// @Tags admin
// @Produce application/json
// @Param id path int true "group id"
// @Success 200 {object} ResetTokenResponse
// @Failure 400 {object} ErrorResponse
// @Failure 401 {object} ErrorResponse
// @Failure 403 {object} ErrorResponse
// @Failure 404 {object} ErrorResponse
// @Failure 500 {object} ErrorResponse
// @Router /admin/subscription-groups/{id}/reset-token [post]
// @ID AdminResetSubscriptionGroupToken
func handleResetGroupToken(w http.ResponseWriter, r *http.Request) {
	id, err := strconv.ParseUint(r.PathValue("id"), 10, 64)
	if err != nil {
		jsonErr(w, http.StatusBadRequest, "invalid id")
		return
	}
	var cnt int
	if err := db.QueryRow("SELECT COUNT(*) FROM subscription_groups WHERE id=?", id).Scan(&cnt); err != nil || cnt == 0 {
		jsonErr(w, http.StatusNotFound, "group not found")
		return
	}

	token, err := generateToken()
	if err != nil {
		jsonErr(w, http.StatusInternalServerError, "token: "+err.Error())
		return
	}
	now := time.Now().UTC().Format("2006-01-02 15:04:05")
	if _, err := db.Exec("UPDATE subscription_groups SET token=?, updated_at=? WHERE id=?", token, now, id); err != nil {
		jsonErr(w, http.StatusInternalServerError, "db: "+err.Error())
		return
	}
	jsonOK(w, ResetTokenResponse{Token: token})
}

// GET /s/{token}  — 公开端点，无需认证
func handlePublicGroupClash(w http.ResponseWriter, r *http.Request) {
	token := r.PathValue("token")
	if len(token) != 64 {
		http.NotFound(w, r)
		return
	}

	var groupID uint
	var groupName string
	err := db.QueryRow("SELECT id, name FROM subscription_groups WHERE token=?", token).Scan(&groupID, &groupName)
	if err != nil {
		http.NotFound(w, r)
		return
	}

	rows, err := db.Query("SELECT node_mac FROM subscription_group_nodes WHERE group_id=?", groupID)
	if err != nil {
		http.Error(w, "db error", http.StatusInternalServerError)
		return
	}
	defer rows.Close()
	var macs []string
	for rows.Next() {
		var mac string
		if rows.Scan(&mac) == nil {
			macs = append(macs, mac)
		}
	}

	nodes, err := queryNodesByMACs(macs)
	if err != nil {
		http.Error(w, "db error", http.StatusInternalServerError)
		return
	}

	yaml := buildGroupClashYAML(groupName, nodes)
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Header().Set("Content-Disposition", fmt.Sprintf(`attachment; filename="hive-%s.yaml"`, groupName))
	fmt.Fprint(w, yaml)
}
