import { execSync } from 'node:child_process';
import fs from 'node:fs';

function rmrf(path) {
  fs.rmSync(path, { recursive: true, force: true });
}

rmrf('./src/generated');
fs.mkdirSync('./src/generated/openapi3', { recursive: true });

console.log('>>> Generating Zod schemas from OpenAPI...');
console.log('>>> Converting Swagger2 -> OpenAPI3...');
execSync(
  'npx --yes swagger2openapi --yaml --outfile ./src/generated/openapi3/openapi.yaml ' +
    '../registry/openapi/openapi.yaml',
  { stdio: 'inherit' },
);

execSync('npx --yes @cerios/openapi-to-zod', { stdio: 'inherit' });

console.log('>>> Generating TypeScript client...');
// Notes:
// - swagger2 spec is generated by swaggo/swag
// - openapi-typescript-codegen generates fetch-based client and types
execSync(
  'npx --yes openapi-typescript-codegen ' +
    '--input ./src/generated/openapi3/openapi.yaml ' +
    '--output ./src/generated/client ' +
    '--client fetch ' +
    '--useOptions',
  { stdio: 'inherit' },
);

console.log('>>> gen-api finished');

