/**
 * gen-themes.mjs — 构建期主题色生成器
 * ---------------------------------------------------------------------------
 * 用官方 @material/material-color-utilities 把每个 Material Design 调色板种子色
 * 算成一整套 Material 3 角色（primary/secondary/tertiary/error + 8 级 surface
 * container + outline/inverse 等），明暗双模各一份,输出为 HSL 三元组 CSS 变量。
 *
 * 产物 styles/themes.css 用 `[data-theme-color="<key>"]` 属性选择器承载,unlayered
 * (在 @layer 之外),因此优先级高于 globals.css 里 @layer base 的默认 Google 蓝,
 * 运行时 ThemeColorProvider 往 <html data-theme-color> 一写整站即换肤。
 * 明/暗用互斥选择器 `:root:not(.dark)[...]` 与 `:root.dark[...]`,不依赖源码顺序。
 *
 * 生成结果已提交入库,CI 无需运行本脚本。种子色或角色映射变更时手动重跑:
 *   node scripts/gen-themes.mjs   (脚本内部用 esbuild 打包以绕过 MCU v0.4 的 ESM
 *   相对导入缺 .js 扩展名 bug)
 */
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { execFileSync } from 'node:child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const UI_ROOT = resolve(__dirname, '..');
const OUT = resolve(UI_ROOT, 'styles/themes.css');

/**
 * 19 个 Material Design 2014 命名调色板 + 说明。key 用于 data-theme-color 属性,
 * seed 取各色 500 号色（Material 官方主色调）。顺序即选择器里的展示顺序。
 * 默认（Google 蓝,globals.css 内联手调值）不在此列 —— 那是 data 属性缺省态。
 */
const SEEDS = [
  { key: 'red', seed: '#F44336' },
  { key: 'pink', seed: '#E91E63' },
  { key: 'purple', seed: '#9C27B0' },
  { key: 'deep-purple', seed: '#673AB7' },
  { key: 'indigo', seed: '#3F51B5' },
  { key: 'blue', seed: '#2196F3' },
  { key: 'light-blue', seed: '#03A9F4' },
  { key: 'cyan', seed: '#00BCD4' },
  { key: 'teal', seed: '#009688' },
  { key: 'green', seed: '#4CAF50' },
  { key: 'light-green', seed: '#8BC34A' },
  { key: 'lime', seed: '#CDDC39' },
  { key: 'yellow', seed: '#FFEB3B' },
  { key: 'amber', seed: '#FFC107' },
  { key: 'orange', seed: '#FF9800' },
  { key: 'deep-orange', seed: '#FF5722' },
  { key: 'brown', seed: '#795548' },
  { key: 'grey', seed: '#9E9E9E' },
  { key: 'blue-grey', seed: '#607D8B' },
];

// CSS 变量名 ← MaterialDynamicColors 角色名 映射。左为 globals.css 消费的 --md-*
// 变量,右为 MCU 的 DynamicColor 属性。覆盖 globals 里声明的全部角色。
const ROLE_MAP = [
  ['--md-primary', 'primary'],
  ['--md-on-primary', 'onPrimary'],
  ['--md-primary-container', 'primaryContainer'],
  ['--md-on-primary-container', 'onPrimaryContainer'],
  ['--md-secondary', 'secondary'],
  ['--md-on-secondary', 'onSecondary'],
  ['--md-secondary-container', 'secondaryContainer'],
  ['--md-on-secondary-container', 'onSecondaryContainer'],
  ['--md-tertiary', 'tertiary'],
  ['--md-on-tertiary', 'onTertiary'],
  ['--md-tertiary-container', 'tertiaryContainer'],
  ['--md-on-tertiary-container', 'onTertiaryContainer'],
  ['--md-error', 'error'],
  ['--md-on-error', 'onError'],
  ['--md-error-container', 'errorContainer'],
  ['--md-on-error-container', 'onErrorContainer'],
  ['--md-surface', 'surface'],
  ['--md-surface-dim', 'surfaceDim'],
  ['--md-surface-bright', 'surfaceBright'],
  ['--md-surface-container-lowest', 'surfaceContainerLowest'],
  ['--md-surface-container-low', 'surfaceContainerLow'],
  ['--md-surface-container', 'surfaceContainer'],
  ['--md-surface-container-high', 'surfaceContainerHigh'],
  ['--md-surface-container-highest', 'surfaceContainerHighest'],
  ['--md-on-surface', 'onSurface'],
  ['--md-on-surface-variant', 'onSurfaceVariant'],
  ['--md-outline', 'outline'],
  ['--md-outline-variant', 'outlineVariant'],
  ['--md-inverse-surface', 'inverseSurface'],
  ['--md-inverse-on-surface', 'inverseOnSurface'],
  ['--md-inverse-primary', 'inversePrimary'],
  ['--md-scrim', 'scrim'],
  ['--md-shadow', 'shadow'],
];

main();

function main() {
  // MCU v0.4 的内部相对导入缺 .js 扩展名,Node ESM 直接 import 会炸;用 esbuild
  // 把一个薄 worker 打成自包含 bundle 再跑,顺带在 worker 里做 argb→HSL 转换。
  const tmp = mkdtempSync(resolve(tmpdir(), 'hive-themes-'));
  const workerSrc = resolve(tmp, 'worker.mjs');
  const workerOut = resolve(tmp, 'worker.bundle.mjs');
  writeFileSync(workerSrc, WORKER());
  execFileSync(
    resolve(UI_ROOT, 'node_modules/.bin/esbuild'),
    [workerSrc, '--bundle', '--platform=node', '--format=esm', `--outfile=${workerOut}`, '--log-level=error'],
    { cwd: UI_ROOT },
  );
  const payload = JSON.stringify({ seeds: SEEDS, roleMap: ROLE_MAP });
  const json = execFileSync('node', [workerOut, payload], { cwd: UI_ROOT }).toString();
  const themes = JSON.parse(json);

  writeFileSync(OUT, renderCss(themes));
  rmSync(tmp, { recursive: true, force: true });
  console.log(`✓ wrote ${OUT} — ${SEEDS.length} themes × 2 modes`);
}

function renderCss(themes) {
  const header = `/* =========================================================================
   themes.css — GENERATED by scripts/gen-themes.mjs. DO NOT EDIT BY HAND.
   Material 3 role tokens for each Material Design palette seed, computed with
   @material/material-color-utilities (SchemeTonalSpot). Consumed by overriding
   the --md-* triplets that globals.css already aliases; runtime picker sets
   <html data-theme-color="<key>">. Light/dark use mutually-exclusive selectors
   so the cascade never depends on source order. Regenerate: node scripts/gen-themes.mjs
   ========================================================================= */\n`;
  const blocks = themes.map((t) => {
    const light = t.light.map(([k, v]) => `    ${k}: ${v};`).join('\n');
    const dark = t.dark.map(([k, v]) => `    ${k}: ${v};`).join('\n');
    return `:root:not(.dark)[data-theme-color='${t.key}'] {\n${light}\n  }\n\n:root.dark[data-theme-color='${t.key}'] {\n${dark}\n  }`;
  });
  return `${header}\n${blocks.join('\n\n')}\n`;
}

// ── worker：在 esbuild bundle 里跑,能安全 import MCU ────────────────────────
function WORKER() {
  return `
import { Hct, SchemeTonalSpot, MaterialDynamicColors, argbFromHex, hexFromArgb } from '@material/material-color-utilities';

const { seeds, roleMap } = JSON.parse(process.argv[2]);
const M = MaterialDynamicColors;

function hexToHslTriplet(hex) {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b), min = Math.min(r, g, b);
  let h = 0, s = 0;
  const l = (max + min) / 2;
  const d = max - min;
  if (d !== 0) {
    s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break;
      case g: h = (b - r) / d + 2; break;
      default: h = (r - g) / d + 4;
    }
    h /= 6;
  }
  const H = Math.round(h * 360);
  const S = Math.round(s * 1000) / 10;
  const L = Math.round(l * 1000) / 10;
  return H + ' ' + S + '% ' + L + '%';
}

function roleset(seedHex, isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(seedHex)), isDark, 0);
  return roleMap.map(([cssVar, role]) => {
    const dc = M[role];
    const hex = hexFromArgb(dc.getArgb(scheme));
    // globals.css consumes these via hsl(var(--md-*)), so store bare triplets.
    return [cssVar, hexToHslTriplet(hex)];
  });
}

const out = seeds.map(({ key, seed }) => ({
  key,
  light: roleset(seed, false),
  dark: roleset(seed, true),
}));
process.stdout.write(JSON.stringify(out));
`;
}
